### PR TITLE
Include Caltables and mask file descriptions

### PR DESCRIPTION
**Pull request by dane-kleiner**

### CODE REVIEW

**Comment by paoloserra** [comment]
Only one file changed, so probably you  didn't do the following?

```
python make_caracal_docs.py
cd sphinx
make html
cd ../
```

**Comment by dane-kleiner** [comment]
> Only one file changed, so probably you didn't do the following?
> 
> ```
> python make_caracal_docs.py
> cd sphinx
> make html
> cd ../
> ```

Nope. I just edited the file on github. So, it's better to edit the file locally, do a make html and then push?

**Comment by paoloserra** [comment]
Yes, you need to, because once we merge this into master https://caracal.readthedocs.io/en/latest is updated automatically based on the files created with `make html`.

**Comment by dane-kleiner** [comment]
> Yes, you need to, because once we merge this into master https://caracal.readthedocs.io/en/latest is updated automatically based on the files created with `make html`.

I see. Perhaps that what messed things up last time. I can do it again?

**Comment by paoloserra** [comment]
No no, last time was my fault.

It's easy enough this time. Just git pull, checkout your branch, run the commands above, and commit to your branch.

**Pull request closed without merging**
