### PR TITLE
Acknowledgements

### PR DESCRIPTION
**Pull request by gigjozsa**
Added acknowledgements and logos, some additional description of caratekit. Notice that this is of course a suggestion, but we need this in a week's time.
Once accepted, update the README.md of the main caracal pages to point to the publication policy on this page.

### CODE REVIEW

**Comment by paoloserra** [comment]
I'm getting lots of errors when running `make html` in your branch. I suppose you're getting them, too. The most important ones are:

```
/Users/pserra/Astro/caracal-docs/sphinx/credits/caracal_logos/index.rst:7: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/Users/pserra/Astro/caracal-docs/sphinx/credits/crediting/index.rst:10: WARNING: Title overline too short.

=====================
CARACal publication policy
=====================
/Users/pserra/Astro/caracal-docs/sphinx/credits/crediting/index.rst:17: WARNING: Title underline too short.

Acknowledging CARACal
________________
/Users/pserra/Astro/caracal-docs/sphinx/credits/crediting/index.rst:76: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/pserra/Astro/caracal-docs/sphinx/credits/crediting/index.rst:50: WARNING: Unknown target name: "a reference to your publication (partly) based on a caracal data reduction<https://github.com/caracal-pipeline/caracal-docs/issues/9>".
/Users/pserra/Astro/caracal-docs/sphinx/credits/index.rst:6: WARNING: Title overline too short.

=======
Acknowledgements
=======
/Users/pserra/Astro/caracal-docs/sphinx/manual/caratekit_utility/index.rst:109: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/pserra/Astro/caracal-docs/sphinx/manual/workers/ddcal/index.rst:297: WARNING: Inline emphasis start-string without end-string.
```

Errors of this kind will affect the layout of the documentation so should be fixed.

**Comment by gigjozsa** [comment]
My intention was to take care of the ones generated in the files that I have changed. The others are inherited and probably better corrected by whoever created them first place?

I thouhgt I'd addressed all of mine, will re-check.

**Comment by paoloserra** [comment]
Nope, the errors above are from your changes.

**Comment by gigjozsa** [comment]
From files I never touched?

**Comment by gigjozsa** [comment]
Ah, they are from the auto-generation

**Comment by gigjozsa** [comment]
@paoloserra could you check if this is ok now?

**Comment by gigjozsa** [comment]
Oh, of course, now I see what has changed.

**Comment by paoloserra** [comment]
OK. I think we need to find a better way to do this

**Pull request merged**
