### PR TITLE
Added carate description

### PR DESCRIPTION
**Pull request by gigjozsa**
Added carate description, edited build script (it only worked every third time for me).

### CODE REVIEW

**Comment by paoloserra** [comment]
Ah, seen the build script, minor changes indeed, it should work for me too!

**Comment by gigjozsa** [comment]
> Something ain't right. In master you can see a sphinx/_build directory. That one contains an html/ directory and subdirectories with all relevant .html files. You can open those with your browser to inspect what the webpage looks like once you update readthedocs. In your branch, however, there is no sphinx/_build directory. Did you run `make html` inside the sphinx directory as per instructions?
> 
> Concerning the script, note that I run python 2.7 on my laptop, so there might be differences from a version required for python 3. I hope your changes work in python 2.7 ,but let's sort out the issue of the missing sphinx/_build directory first

Just edit and merge as you see fit.

**Comment by paoloserra** [comment]
> Just edit and merge as you see fit.

Can you confirm that you run `make html`?

**Comment by gigjozsa** [comment]
Yes, but before committing I removed stuff, I think.

**Comment by paoloserra** [comment]
OK. Can you `make html` and commit without removing anything, to see whether it's all OK?

**Comment by gigjozsa** [comment]
Done, I only get a few warnings about new names

**Pull request merged**
